# Generated by Django 3.0.3 on 2020-07-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrassDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Growth_type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Common_N', models.CharField(blank=True, max_length=200)),
                ('Scientific_N', models.CharField(blank=True, max_length=200)),
                ('Wiki', models.CharField(blank=True, max_length=200)),
                ('Genbank', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'grassdb',
            },
        ),
    ]
